---
title: "yld_analysis"
author: "Daniel Lu"
date: "6/7/2020"
output: html_document
---


Prior to analyzing the trends present in our YLD visualization, it is important to know that, since there was no information on the specific disorders that an individual had, I used disability weights for classifications of illness (e.g. Mood Disorders, Anxiety Disorders, etc.). These were calculated by averaging together the disability weights for each of the illnesses within that classification. Additionally, as there was little information given on individuals with more than one illness, comorbidity was not taken into account. 

Now, as we can see from our Years Lived with Disability visualization, there is absolutely a difference between the YLDs experienced by our 1400-person tech industry sample and a representative 1400-person sample from the general population - to the tune of 247.6808 YLDs for tech and 117.2296 for the general population. This is a stunning difference, much of which comes from the 'Mood Disorders' category, which includes Major Depressive Disorder and Bipolar Disorder, where tech workers see over 4 times the YLDs of the general population sample. The disorders in this category are caused (environmentally) by long periods of high stress, traumatic events, and learned helplessness. The fact that Mood Disorders are so prevalent in the tech industry as compared to the general population may imply a stressful and fast-paced environment where many expect perfection out of themselves and judge themselves harshly if they fail in achieving that. Also of note is the Substance Use Disorder category, where the general population sees just over three times the total YLDs. The fact that the prevalence of this category is so low for tech workers, while the majority of other categories see increased YLDs for tech workers vs the general population, leads me to believe that on the job stress is either being internalized, which seems likely, or relieved via other methods, like physical exercise or entertainment. Given additional resources, this could be an avenue of exploration - the effectiveness of 'fitness budgets' and other stress relief initiatives pushed out by major companies.